"""
Django settings for equi_media_portal project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rsqzrx)%d)f^50@!kf=5e2j3(xswm#ntxt=%dh9e$nrbniw_d*'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
#
# ALLOWED_HOSTS = ['ipsoru68.beget.tech', 'www.ipsoru68.beget.tech']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.sites',
#     'django.contrib.flatpages',
#
#     'portal.apps.PortalConfig',
#     'articles.apps.ArticlesConfig',
#     'news.apps.NewsConfig',
#     'slider.apps.SliderConfig',
#     'testimonial.apps.TestimonialConfig',
#     'ckeditor',
#     'el_pagination'
# ]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    'event.apps.EventConfig',
    'portal.apps.PortalConfig',
    'articles.apps.ArticlesConfig',
    'news.apps.NewsConfig',
    'slider.apps.SliderConfig',
    'testimonial.apps.TestimonialConfig',
    'ckeditor',
    'el_pagination'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'equi_media_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portal.context_processors.website_settings',
                'portal.context_processors.load_settings',
                'django.template.context_processors.request',  ## For EL-pagination
            ],
        },
    },
]

WSGI_APPLICATION = 'equi_media_portal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ipsoru68_equip',
# 	'USER': 'ipsoru68_equip',
#         'PASSWORD': 'Zxcv0987',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'equimedia',
        'USER': 'admin',
        'PASSWORD': 'zxcv0987',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

DISCIPLINE = [('Вестерн', _('Вестерн')),
              ('Вольтижировка', _('Вольтижировка')),
              ('Выездка', _('Выездка')),
              ('Джигитовка', _('Джигитовка')),
              ('Драйвинг', _('Драйвинг')),
              ('Конкур', _('Конкур')),
              ('Паравыездка', _('Паравыездка')),
              ('Пони-спорт', _('Пони-спорт')),
              ('Пробеги', _('Пробеги')),
              ('Тентпеггинг', _('Тентпеггинг')),
              ('Троеборье', _('Троеборье')),
              ('Хобби-хорсинг', _('Хобби-хорсинг'))]

CONTEST_TYPE = [('Всероссийский', _('Всероссийский')),
                ('Международный', _('Международный')),
                ('Муниципальный', _('Муниципальный')),
                ('Клубный', _('Клубный')),
                ('Региональный', _('Региональный'))]

EVENT_TYPE = [(1, _('Аукционы')),
              (2, _('Выставки')),
              (3, _('Конференции')),
              (4, _('Мастер-классы')),
              (5, _('Семинары')),
              (6, _('Тренировки'))
              ]

STAGE_TYPE = [('Соревнования', _('Соревнования')),
              ]

PER_PAGE = 9
